name: researcher
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - aom=3.5.0
  - appdirs=1.4.4
  - arrow-cpp=11.0.0
  - arxiv=1.4.3
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attr=2.5.1
  - attrs=22.2.0
  - aws-c-auth=0.6.24
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.10
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.18
  - aws-c-http=0.7.4
  - aws-c-io=0.13.15
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.4
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.7
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.7
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.7.0
  - cycler=0.11.0
  - dataclasses=0.8
  - datasets=2.9.0
  - dbus=1.13.6
  - debugpy=1.6.6
  - decorator=5.1.1
  - dill=0.3.6
  - executing=1.2.0
  - expat=2.5.0
  - faiss=1.7.2
  - feedparser=6.0.10
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - filelock=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.1.0
  - fuzzywuzzy=0.18.0
  - gettext=0.21.1
  - gflags=2.2.2
  - glib=2.74.1
  - glib-tools=2.74.1
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.33
  - harfbuzz=6.0.0
  - huggingface_hub=0.12.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.10.2
  - ipykernel=6.21.2
  - ipython=8.10.0
  - jack=1.9.22
  - jedi=0.18.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=8.0.3
  - jupyter_core=5.2.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - levenshtein=0.20.9
  - libabseil=20220623.0
  - libarrow=11.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.5.1.14
  - libcups=2.3.3
  - libcurand=10.3.1.124
  - libcurl=7.88.0
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libfaiss=1.7.2
  - libfaiss-avx2=1.7.2
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc=7.2.0
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgoogle-cloud=2.7.0
  - libgpg-error=1.46
  - libgrpc=1.51.1
  - libhwloc=2.8.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm15=15.0.7
  - libnghttp2=1.51.0
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libogg=1.3.4
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.21.12
  - libsentencepiece=0.1.97
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtasn1=4.19.0
  - libthrift=0.16.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libva=2.17.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - llvmlite=0.39.1
  - lz4-c=1.9.4
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.1.0
  - mpg123=1.31.2
  - mpmath=1.2.1
  - multidict=6.0.4
  - multiprocess=0.70.14
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - nltk=3.8.1
  - nspr=4.35
  - nss=3.88
  - numba=0.56.4
  - numpy=1.23.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.0.8
  - orc=1.8.2
  - p11-kit=0.24.1
  - packaging=23.0
  - pandas=1.5.3
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - pcre2=10.40
  - pdf2image=1.16.2
  - pdfminer=20191125
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.0.0
  - plotly=5.13.0
  - ply=3.11
  - pooch=1.6.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pycryptodome=3.16.0
  - pygments=2.14.0
  - pynndescent=0.5.8
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-levenshtein=0.20.9
  - python-xxhash=3.2.0
  - python_abi=3.10
  - pytorch=2.0.0.dev20230219
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7.1
  - pyyaml=6.0
  - pyzmq=25.0.0
  - qt-main=5.15.8
  - rapidfuzz=2.13.7
  - re2=2023.02.01
  - readline=8.1.2
  - regex=2022.10.31
  - requests=2.28.2
  - responses=0.18.0
  - s2n=1.3.35
  - sacremoses=0.0.53
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - sentence-transformers=2.2.2
  - sentencepiece=0.1.97
  - sentencepiece-python=0.1.97
  - sentencepiece-spm=0.1.97
  - setuptools=67.3.2
  - sgmllib3k=1.0.0
  - sip=6.7.7
  - six=1.16.0
  - snappy=1.1.9
  - stack_data=0.6.2
  - svt-av1=1.4.1
  - sympy=1.11.1
  - tbb=2021.7.0
  - tenacity=8.2.1
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tokenizers=0.13.2
  - toml=0.10.2
  - torchaudio=2.0.0.dev20230219
  - torchtriton=2.0.0+c8bfe3f548
  - torchvision=0.15.0.dev20230219
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.9.0
  - transformers=4.26.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - umap-learn=0.5.3
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - wheel=0.38.4
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zeromq=4.3.4
  - zipp=3.14.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - altair==4.2.2
      - async-generator==1.10
      - blinker==1.5
      - cachetools==5.3.0
      - cython==0.29.33
      - dataclasses-json==0.5.7
      - entrypoints==0.4
      - exceptiongroup==1.1.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-search-results==2.4.1
      - greenlet==2.0.2
      - h11==0.14.0
      - jinja2==3.1.2
      - langchain==0.0.89
      - markdown-it-py==2.1.0
      - markupsafe==2.1.2
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - mdurl==0.1.2
      - mypy-extensions==1.0.0
      - outcome==1.2.0
      - protobuf==3.20.3
      - pyarrow==11.0.0
      - pydantic==1.10.5
      - pydeck==0.8.0
      - pympler==1.0.1
      - pytz-deprecation-shim==0.1.0.post0
      - rich==13.3.1
      - selectolax==0.3.12
      - selenium==4.8.2
      - selenium-stealth==1.0.6
      - semver==2.13.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - sqlalchemy==1.4.46
      - streamlit==1.18.1
      - toolz==0.12.0
      - trio==0.22.0
      - trio-websocket==0.9.2
      - typing-inspect==0.8.0
      - tzdata==2022.7
      - tzlocal==4.2
      - validators==0.20.0
      - watchdog==2.2.1
      - wsproto==1.2.0
